services:
  mysql:
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reddit-net
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - reddit-net

networks:
  reddit-net:
    name: reddit-net

volumes:
  redis_data:
  mysql_data:
